# Generated by Django 5.1.3 on 2024-11-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('booked', models.BooleanField(default=False)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('available_slots', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guests', models.IntegerField()),
                ('confirmed', models.BooleanField(default=False)),
                ('comments_user', models.CharField(blank=True, max_length=1024, null=True)),
                ('comments_staff', models.CharField(blank=True, max_length=1024, null=True)),
                ('booked_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.availability')),
            ],
        ),
    ]
