# Generated by Django 5.1.3 on 2024-11-20 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='event',
            name='available_slots',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking.availability'),
        ),
    ]
