# Generated by Django 5.1.3 on 2024-11-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_availability_event_remove_customuser_groups_and_more'),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.customuser'),
        ),
        migrations.AddField(
            model_name='availability',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.event'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
