# Generated by Django 5.1.3 on 2024-11-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_event_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
