# Generated by Django 5.1.3 on 2024-11-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_event_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
