# Generated by Django 5.1.3 on 2024-11-21 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_booked_slot_booking_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guests',
        ),
    ]
